### ISSUE TITLE
Blockchain Error: Failed to parse transaction from blob

### ISSUE THREAD

**Issue by jodobear** [sumoprojects/sumokoin#135]
Hi guys, I started my weekly scheduled sync for the blockchain and got the following anomaly:

`2018-Jun-11 22:25:44.799110 [P2P9][178.114.251.244:65471 INC]Sync data returned a new top block candidate: 139855 -> 141032 [Your node is 1177 blocks (3 days) behind]
SYNCHRONIZATION started
2018-Jun-11 22:25:47.897908 [P2P2]ERROR C:/msys64/home/Admin/sumokoin/src/cryptonote_core/cryptonote_format_utils.cpp:102 Failed to parse transaction from blob
2018-Jun-11 22:25:48.672851 [P2P9][83.59.139.132:55962 INC]Sync data returned a new top block candidate: 139855 -> 143894 [Your node is 4039 blocks (11 days) behind]
SYNCHRONIZATION started
2018-Jun-11 22:25:50.438435 [P2P2]ERROR C:/msys64/home/Admin/sumokoin/src/cryptonote_core/cryptonote_format_utils.cpp:102 Failed to parse transaction from blob`

That is snippet of the daemon log. It kept repeating this for over an hour from `11days` to `3 days` while i was away.

Has anybody had this? It looks like my DB is corrupted. But, this is a strange behavior for db corruption i have come across. Any explanation would be helpful.

Thanks!

**Comment by radbud** [comment]
Here is the complete log after i initiated v0-3-1-0. I am currently running win.x64:

`Creating the logger system
2018-Jun-12 19:01:02.219096 Initializing cryptonote protocol...
2018-Jun-12 19:01:02.219096 Cryptonote protocol initialized OK
2018-Jun-12 19:01:02.224124 Initializing p2p server...
2018-Jun-12 19:01:02.658791 Set limit-up to 2048 kB/s
2018-Jun-12 19:01:02.658791 Set limit-down to 8192 kB/s
2018-Jun-12 19:01:02.660313 Set limit-up to 2048 kB/s
2018-Jun-12 19:01:02.660313 Set limit-down to 8192 kB/s
2018-Jun-12 19:01:02.689312 Binding on 0.0.0.0:19733
2018-Jun-12 19:01:02.689312 Net service bound to 0.0.0.0:19733
2018-Jun-12 19:01:02.694337 Attempting to add IGD port mapping.
2018-Jun-12 19:01:04.323775 Added IGD port mapping.
2018-Jun-12 19:01:04.323775 P2p server initialized OK
2018-Jun-12 19:01:04.323775 Initializing core rpc server...
2018-Jun-12 19:01:04.323775 Binding on 127.0.0.1:19734
2018-Jun-12 19:01:04.323775 Core rpc server initialized OK on port: 19734
2018-Jun-12 19:01:04.323775 Initializing core...
2018-Jun-12 19:01:04.339555 Loading blockchain from folder C:\ProgramData\sumokoin\lmdb ...
2018-Jun-12 19:01:04.339555 option: fast
2018-Jun-12 19:01:04.339555 option: async
2018-Jun-12 19:01:04.341581 option: 1000
2018-Jun-12 19:01:04.634561 Blockchain initialized. last block: 139873, d0.h19.m35.s17 time ago, current difficulty: 3007450
2018-Jun-12 19:01:04.985438 WARNING: no two valid SumoPulse DNS checkpoint records were received
2018-Jun-12 19:01:04.987498 Core initialized OK
2018-Jun-12 19:01:04.987498 Starting core rpc server...
2018-Jun-12 19:01:04.994026 Run net_service loop( 4 threads)...
2018-Jun-12 19:01:04.994026 [SRV_MAIN]Core rpc server started ok
2018-Jun-12 19:01:04.995559 [SRV_MAIN]Starting p2p net loop...
2018-Jun-12 19:01:04.995559 [SRV_MAIN]Run net_service loop( 10 threads)...
2018-Jun-12 19:01:06.014133 [P2P7]
**********************************************************************
The daemon will start synchronizing with the network. It may take up to several hours.

You can set the level of process detailization* through "set_log <level>" command*, where <level> is between 0 (no details) and 4 (very verbose).

Use "help" command to see the list of available commands.

Note: in case you need to interrupt the process, use "exit" command. Otherwise, the current progress won't be saved.
**********************************************************************
2018-Jun-12 19:01:06.796679 [P2P7][42.200.247.88:19733 OUT]Sync data returned a new top block candidate: 139874 -> 140153 [Your node is 279 blocks (0 days) behind]
SYNCHRONIZATION started
2018-Jun-12 19:01:07.174716 [P2P7][46.138.19.211:19733 OUT]Sync data returned a new top block candidate: 139874 -> 141330 [Your node is 1456 blocks (4 days) behind]
SYNCHRONIZATION started
2018-Jun-12 19:01:08.745309 [P2P6][42.200.247.88:19733 OUT]Synced 139884/141330
2018-Jun-12 19:01:09.814593 [P2P9][42.200.247.88:19733 OUT]Synced 139894/141330
2018-Jun-12 19:01:11.576883 [P2P5][42.200.247.88:19733 OUT]Synced 139904/141330
2018-Jun-12 19:01:13.184562 [P2P9][42.200.247.88:19733 OUT]Synced 139914/141330
2018-Jun-12 19:01:14.549059 [P2P9]ERROR C:/msys64/home/QUANGVH/sumokoin/src/cryptonote_core/cryptonote_format_utils.cpp:102 Failed to parse transaction from blob
2018-Jun-12 19:01:16.568149 [P2P6][42.200.247.88:19733 OUT]Synced 139924/141330
2018-Jun-12 19:01:18.077070 [P2P9][185.243.112.196:19733 OUT]Sync data returned a new top block candidate: 139924 -> 141331 [Your node is 1407 blocks (3 days) behind]
SYNCHRONIZATION started
2018-Jun-12 19:01:18.924646 [P2P5][42.200.247.88:19733 OUT]Synced 139934/141331
2018-Jun-12 19:01:20.004645 [P2P9]ERROR C:/msys64/home/QUANGVH/sumokoin/src/cryptonote_core/cryptonote_format_utils.cpp:102 Failed to parse transaction from blob
2018-Jun-12 19:01:20.507430 [P2P7][42.200.247.88:19733 OUT]Synced 139944/141331
2018-Jun-12 19:01:21.712524 [P2P7][42.200.247.88:19733 OUT]Synced 139954/141331
2018-Jun-12 19:01:22.935611 [P2P7][42.200.247.88:19733 OUT]Synced 139964/141331
2018-Jun-12 19:01:23.486433 [P2P7]
**********************************************************************
You are now synchronized with the network. You may now start sumo-wallet-cli.

Please note, that the blockchain will be saved only after you quit the daemon with "exit" command or if you use "save" command.
Otherwise, you will possibly need to synchronize the blockchain again.

Use "help" command to see the list of available commands.
**********************************************************************
2018-Jun-12 19:01:27.796828 [P2P4][42.200.247.88:19733 OUT]Synced 139974/141331
2018-Jun-12 19:01:29.467193 [P2P9][42.200.247.88:19733 OUT]Synced 139984/141331
2018-Jun-12 19:01:31.246970 [P2P6][42.200.247.88:19733 OUT]Synced 139994/141331
2018-Jun-12 19:01:32.835628 [P2P6][42.200.247.88:19733 OUT]Synced 140004/141331
2018-Jun-12 19:01:34.128731 [P2P7][42.200.247.88:19733 OUT]Synced 140014/141331
2018-Jun-12 19:01:34.437023 [P2P9][88.95.24.5:19733 OUT]Sync data returned a new top block candidate: 140014 -> 141331 [Your node is 1317 blocks (3 days) behind]
SYNCHRONIZATION started
2018-Jun-12 19:01:35.577390 [P2P7][42.200.247.88:19733 OUT]Synced 140024/141331
2018-Jun-12 19:01:36.676498 [P2P9]ERROR C:/msys64/home/QUANGVH/sumokoin/src/cryptonote_core/cryptonote_format_utils.cpp:102 Failed to parse transaction from blob
2018-Jun-12 19:01:36.848539 [P2P9][79.167.162.70:19733 OUT]Sync data returned a new top block candidate: 140027 -> 140153 [Your node is 126 blocks (0 days) behind]
SYNCHRONIZATION started
2018-Jun-12 19:01:38.140190 [P2P7][42.200.247.88:19733 OUT]Synced 140034/140153
2018-Jun-12 19:01:39.226373 [P2P4][42.200.247.88:19733 OUT]Synced 140044/140153
2018-Jun-12 19:01:40.285680 [P2P9][98.21.220.85:19733 OUT]Sync data returned a new top block candidate: 140044 -> 141331 [Your node is 1287 blocks (3 days) behind]
SYNCHRONIZATION started
2018-Jun-12 19:01:40.304941 [P2P7][42.200.247.88:19733 OUT]Synced 140054/141331
2018-Jun-12 19:01:41.491509 [P2P7][42.200.247.88:19733 OUT]Synced 140064/141331
2018-Jun-12 19:01:42.780829 [P2P9][42.200.247.88:19733 OUT]Synced 140074/141331
2018-Jun-12 19:01:44.096708 [P2P7][42.200.247.88:19733 OUT]Synced 140084/141331
2018-Jun-12 19:01:45.245007 [P2P4][42.200.247.88:19733 OUT]Synced 140094/141331
2018-Jun-12 19:01:46.328168 [P2P4][42.200.247.88:19733 OUT]Synced 140104/141331
2018-Jun-12 19:01:47.427580 [P2P6][42.200.247.88:19733 OUT]Synced 140114/141331
2018-Jun-12 19:01:48.568509 [P2P4][42.200.247.88:19733 OUT]Synced 140124/141331
2018-Jun-12 19:01:49.805098 [P2P9][42.200.247.88:19733 OUT]Synced 140134/141331
2018-Jun-12 19:01:51.196948 [P2P6][42.200.247.88:19733 OUT]Synced 140144/141331
2018-Jun-12 19:01:52.285871 [P2P6][42.200.247.88:19733 OUT]Synced 140153/141331
2018-Jun-12 19:01:52.287918 [P2P6][42.200.247.88:19733 OUT] SYNCHRONIZED OK
2018-Jun-12 19:01:53.233915 [P2P4][80.4.222.253:19733 OUT]Sync data returned a new top block candidate: 140153 -> 144196 [Your node is 4043 blocks (11 days) behind]
SYNCHRONIZATION started
2018-Jun-12 19:02:03.747904 [P2P8]ERROR C:/msys64/home/QUANGVH/sumokoin/src/cryptonote_core/cryptonote_format_utils.cpp:102 Failed to parse transaction from blob
2018-Jun-12 19:02:21.664554 [P2P8][42.112.80.15:8141 INC]Sync data returned a new top block candidate: 140153 -> 144196 [Your node is 4043 blocks (11 days) behind]
SYNCHRONIZATION started
2018-Jun-12 19:02:31.436284 [P2P8][117.141.115.7:6928 INC]Sync data returned a new top block candidate: 140153 -> 144196 [Your node is 4043 blocks (11 days) behind]
SYNCHRONIZATION started`

The previous version was 0-3-0-0.

**Comment by radbud** [comment]
Here is the complete daemon log from today using win.x64.v0-3-1-0:

`Creating the logger system
2018-Jun-12 19:01:02.219096 Initializing cryptonote protocol...
2018-Jun-12 19:01:02.219096 Cryptonote protocol initialized OK
2018-Jun-12 19:01:02.224124 Initializing p2p server...
2018-Jun-12 19:01:02.658791 Set limit-up to 2048 kB/s
2018-Jun-12 19:01:02.658791 Set limit-down to 8192 kB/s
2018-Jun-12 19:01:02.660313 Set limit-up to 2048 kB/s
2018-Jun-12 19:01:02.660313 Set limit-down to 8192 kB/s
2018-Jun-12 19:01:02.689312 Binding on 0.0.0.0:19733
2018-Jun-12 19:01:02.689312 Net service bound to 0.0.0.0:19733
2018-Jun-12 19:01:02.694337 Attempting to add IGD port mapping.
2018-Jun-12 19:01:04.323775 Added IGD port mapping.
2018-Jun-12 19:01:04.323775 P2p server initialized OK
2018-Jun-12 19:01:04.323775 Initializing core rpc server...
2018-Jun-12 19:01:04.323775 Binding on 127.0.0.1:19734
2018-Jun-12 19:01:04.323775 Core rpc server initialized OK on port: 19734
2018-Jun-12 19:01:04.323775 Initializing core...
2018-Jun-12 19:01:04.339555 Loading blockchain from folder C:\ProgramData\sumokoin\lmdb ...
2018-Jun-12 19:01:04.339555 option: fast
2018-Jun-12 19:01:04.339555 option: async
2018-Jun-12 19:01:04.341581 option: 1000
2018-Jun-12 19:01:04.634561 Blockchain initialized. last block: 139873, d0.h19.m35.s17 time ago, current difficulty: 3007450
2018-Jun-12 19:01:04.985438 WARNING: no two valid SumoPulse DNS checkpoint records were received
2018-Jun-12 19:01:04.987498 Core initialized OK
2018-Jun-12 19:01:04.987498 Starting core rpc server...
2018-Jun-12 19:01:04.994026 Run net_service loop( 4 threads)...
2018-Jun-12 19:01:04.994026 [SRV_MAIN]Core rpc server started ok
2018-Jun-12 19:01:04.995559 [SRV_MAIN]Starting p2p net loop...
2018-Jun-12 19:01:04.995559 [SRV_MAIN]Run net_service loop( 10 threads)...
2018-Jun-12 19:01:06.014133 [P2P7]
**********************************************************************
The daemon will start synchronizing with the network. It may take up to several hours.

You can set the level of process detailization* through "set_log <level>" command*, where <level> is between 0 (no details) and 4 (very verbose).

Use "help" command to see the list of available commands.

Note: in case you need to interrupt the process, use "exit" command. Otherwise, the current progress won't be saved.
**********************************************************************
2018-Jun-12 19:01:06.796679 [P2P7][42.200.247.88:19733 OUT]Sync data returned a new top block candidate: 139874 -> 140153 [Your node is 279 blocks (0 days) behind]
SYNCHRONIZATION started
2018-Jun-12 19:01:07.174716 [P2P7][46.138.19.211:19733 OUT]Sync data returned a new top block candidate: 139874 -> 141330 [Your node is 1456 blocks (4 days) behind]
SYNCHRONIZATION started
2018-Jun-12 19:01:08.745309 [P2P6][42.200.247.88:19733 OUT]Synced 139884/141330
2018-Jun-12 19:01:09.814593 [P2P9][42.200.247.88:19733 OUT]Synced 139894/141330
2018-Jun-12 19:01:11.576883 [P2P5][42.200.247.88:19733 OUT]Synced 139904/141330
2018-Jun-12 19:01:13.184562 [P2P9][42.200.247.88:19733 OUT]Synced 139914/141330
2018-Jun-12 19:01:14.549059 [P2P9]ERROR C:/msys64/home/QUANGVH/sumokoin/src/cryptonote_core/cryptonote_format_utils.cpp:102 Failed to parse transaction from blob
2018-Jun-12 19:01:16.568149 [P2P6][42.200.247.88:19733 OUT]Synced 139924/141330
2018-Jun-12 19:01:18.077070 [P2P9][185.243.112.196:19733 OUT]Sync data returned a new top block candidate: 139924 -> 141331 [Your node is 1407 blocks (3 days) behind]
SYNCHRONIZATION started
2018-Jun-12 19:01:18.924646 [P2P5][42.200.247.88:19733 OUT]Synced 139934/141331
2018-Jun-12 19:01:20.004645 [P2P9]ERROR C:/msys64/home/QUANGVH/sumokoin/src/cryptonote_core/cryptonote_format_utils.cpp:102 Failed to parse transaction from blob
2018-Jun-12 19:01:20.507430 [P2P7][42.200.247.88:19733 OUT]Synced 139944/141331
2018-Jun-12 19:01:21.712524 [P2P7][42.200.247.88:19733 OUT]Synced 139954/141331
2018-Jun-12 19:01:22.935611 [P2P7][42.200.247.88:19733 OUT]Synced 139964/141331
2018-Jun-12 19:01:23.486433 [P2P7]
**********************************************************************
You are now synchronized with the network. You may now start sumo-wallet-cli.

Please note, that the blockchain will be saved only after you quit the daemon with "exit" command or if you use "save" command.
Otherwise, you will possibly need to synchronize the blockchain again.

Use "help" command to see the list of available commands.
**********************************************************************
2018-Jun-12 19:01:27.796828 [P2P4][42.200.247.88:19733 OUT]Synced 139974/141331
2018-Jun-12 19:01:29.467193 [P2P9][42.200.247.88:19733 OUT]Synced 139984/141331
2018-Jun-12 19:01:31.246970 [P2P6][42.200.247.88:19733 OUT]Synced 139994/141331
2018-Jun-12 19:01:32.835628 [P2P6][42.200.247.88:19733 OUT]Synced 140004/141331
2018-Jun-12 19:01:34.128731 [P2P7][42.200.247.88:19733 OUT]Synced 140014/141331
2018-Jun-12 19:01:34.437023 [P2P9][88.95.24.5:19733 OUT]Sync data returned a new top block candidate: 140014 -> 141331 [Your node is 1317 blocks (3 days) behind]
SYNCHRONIZATION started
2018-Jun-12 19:01:35.577390 [P2P7][42.200.247.88:19733 OUT]Synced 140024/141331
2018-Jun-12 19:01:36.676498 [P2P9]ERROR C:/msys64/home/QUANGVH/sumokoin/src/cryptonote_core/cryptonote_format_utils.cpp:102 Failed to parse transaction from blob
2018-Jun-12 19:01:36.848539 [P2P9][79.167.162.70:19733 OUT]Sync data returned a new top block candidate: 140027 -> 140153 [Your node is 126 blocks (0 days) behind]
SYNCHRONIZATION started
2018-Jun-12 19:01:38.140190 [P2P7][42.200.247.88:19733 OUT]Synced 140034/140153
2018-Jun-12 19:01:39.226373 [P2P4][42.200.247.88:19733 OUT]Synced 140044/140153
2018-Jun-12 19:01:40.285680 [P2P9][98.21.220.85:19733 OUT]Sync data returned a new top block candidate: 140044 -> 141331 [Your node is 1287 blocks (3 days) behind]
SYNCHRONIZATION started
2018-Jun-12 19:01:40.304941 [P2P7][42.200.247.88:19733 OUT]Synced 140054/141331
2018-Jun-12 19:01:41.491509 [P2P7][42.200.247.88:19733 OUT]Synced 140064/141331
2018-Jun-12 19:01:42.780829 [P2P9][42.200.247.88:19733 OUT]Synced 140074/141331
2018-Jun-12 19:01:44.096708 [P2P7][42.200.247.88:19733 OUT]Synced 140084/141331
2018-Jun-12 19:01:45.245007 [P2P4][42.200.247.88:19733 OUT]Synced 140094/141331
2018-Jun-12 19:01:46.328168 [P2P4][42.200.247.88:19733 OUT]Synced 140104/141331
2018-Jun-12 19:01:47.427580 [P2P6][42.200.247.88:19733 OUT]Synced 140114/141331
2018-Jun-12 19:01:48.568509 [P2P4][42.200.247.88:19733 OUT]Synced 140124/141331
2018-Jun-12 19:01:49.805098 [P2P9][42.200.247.88:19733 OUT]Synced 140134/141331
2018-Jun-12 19:01:51.196948 [P2P6][42.200.247.88:19733 OUT]Synced 140144/141331
2018-Jun-12 19:01:52.285871 [P2P6][42.200.247.88:19733 OUT]Synced 140153/141331
2018-Jun-12 19:01:52.287918 [P2P6][42.200.247.88:19733 OUT] SYNCHRONIZED OK
2018-Jun-12 19:01:53.233915 [P2P4][80.4.222.253:19733 OUT]Sync data returned a new top block candidate: 140153 -> 144196 [Your node is 4043 blocks (11 days) behind]
SYNCHRONIZATION started
2018-Jun-12 19:02:03.747904 [P2P8]ERROR C:/msys64/home/QUANGVH/sumokoin/src/cryptonote_core/cryptonote_format_utils.cpp:102 Failed to parse transaction from blob
2018-Jun-12 19:02:21.664554 [P2P8][42.112.80.15:8141 INC]Sync data returned a new top block candidate: 140153 -> 144196 [Your node is 4043 blocks (11 days) behind]
SYNCHRONIZATION started
2018-Jun-12 19:02:31.436284 [P2P8][117.141.115.7:6928 INC]Sync data returned a new top block candidate: 140153 -> 144196 [Your node is 4043 blocks (11 days) behind]
SYNCHRONIZATION started`

The previous log is using win.x64.v0-3-0-0

**Comment by sumoprojects** [comment]
-- Resolved
