### ISSUE TITLE
Can't access an old wallet on the new CLI

### ISSUE THREAD

**Issue by lkjimy** [sumoprojects/sumokoin#698]
Getting the folowing log when trying to open the wallet on the CLI:
(The CLI closes with an error after giving it the password.)

``
INFO	logging	contrib/epee/src/mlog.cpp:273	New log categories: *:WARNING,net:FATAL,net.http:FATAL,net.ssl:FATAL,net.p2p:FATAL,net.cn:FATAL,global:INFO,verify:FATAL,serialization:FATAL,daemon.rpc.payment:ERROR,stacktrace:INFO,logging:INFO,msgwriter:INFO
``

1 - A file named "sumowallet.unportable" is created.
2 - I was able to access using the old version in wich it was created (win.x64.v0-3-4-0).
3 - I wasn't able import the wallet neither by using the seed or file itself on the web wallet.
4 - The network sync seem to have "converted" the blockchain cache to it's new one, so, I didn't try to run the old sumokoind again.

**Comment by sumogr** [comment]
ok listen. let the web wallet be its an old wallet cache issue you are having.
Since you have the seed words safe do the following basic stuff.
Delete all binaries from your sumokoin folder including the wallet files and download the latest release.
Unzip the new binaries in there
Since you are on windows double click **sumokoind.exe** and let the daemon running
then open a command prompt at the location you have unzipped the binaries and type 
**sumo-wallet-cli.exe --restore-deterministic-wallet** 
Follow the instructions and paste your seed words when prompted. Scan the chain from 0 when asked.
It should be working now

**Comment by sumogr** [comment]
No feedback so it's considered resolved

**Comment by lkjimy** [comment]
Thank you. I was able to access my wallet.
