### ISSUE TITLE
Non-Default LMDB Location

### ISSUE THREAD

**Issue by prometx** [sumoprojects/sumokoin#78]
In my increasing syncing of various blockchains, I've found disk space to be at a premium. Is there a way to get the Sumo wallet (Debian Linux) to sync the chain to an external drive?

**Comment by sumogr** [comment]
Creat a folder on the external drive, say E:\sumochain and copy the contents of the C:\Programdata\sumokoin\lmdb folder in there (you can delete the lmdb folder after you do that in order to save space on your main drive)
Now run the daemon with the following flag
./sumokoind --data-dir E:\sumochain
That should do it
Unfortunately there are no flag inputs field on the GUI wallet and the above works only with the cli (Hopefully one with a deamon flags input field will be released soon)

**Comment by sumoprojects** [comment]
Solved, closed
