### ISSUE TITLE
SUMOKOIN HARDWARE WALLET - DISCUSSION

### ISSUE THREAD

**Issue by sumogr** [sumoprojects/sumokoin#96]
@gustavoz will be taking up designing and prototyping Sumokoin's hardware wallet. He is an FPGA/ASIC (embedded hardware) designer with lots of experience on Trezor. He will present here his roadmap and progress (till this project gets its own space here). Everyone can contribute ideas and suggestions but please keep in mind that the main features of Sumokoin's H/W wallet will be absolute security and ease of use (So please avoid suggesting fancy features and help us focus on these two goals)

**Comment by pwhelan** [comment]
What kind of hardware will be used? Has there been any thoughts on how to design the secure element?

**Comment by Allochtoon** [comment]
Please note this is just an unofficial concept proposal incorporating elements by brainstorming with @gustavoz 

This 'revolver' concept separates the user required pincode into a NFC stored key, or a sequence of it user selected by rotation of the disc, and then requiring a PIN / mnemonic word(s). 

So for auth example; 
user rotates to '1' on the disc, and then inputs '01234'

Or even a sequence on the rotary disc, like an mechanical vault mechanism:
user rotates '1, 15, 1, 15', on the disc, and inputs  'banana sushi pancake'

The benefit of a rotational encoder (basically the disc) is faster user input which helps to produce a stronger PIN / mnemonic, and faster user interaction with the menu. Also, it could be used to scroll the full length of the Sumo........... address string for TX verification. 

The A & B user buttons have underneath them RGB LEDs which indicate user expected actions, like red = NO, green = ACCEPT, blue = please note. A hardware buzzer/vibrator might be integrated as well, but i don't see how it could be used to add user interaction value at the moment. It might also break down. 

On the disc itself, each NFC chip has its own antenna etched on the PCB, barely strong enough to be readable by the reader on the NFC 'RX TX' on the PCB just ~.5mm away from the designated NFC user selected chip. 

Maybe the 16 NFC chips together can be used some other useful way to store data of ghost addresses being used, or what not, but i'm not cryptographically versed to say if that would introduce attack vectors or not. The benefit of NFC chips with small antenna's is that they can be passively read and written, so no direct electrical contact with the main PCB is needed. 

Now i can imagine it would complicate too much or, not really add security, it's just a thought.

Considering the design, i'm gravitating towards proposing to encasing the hardware wallet in natural bamboo, comprised like a closing shell to protect the display with the Sumokoin logo etched on the back of it. Bamboo imho is the perfect material to accompany the brand of Sumokoin and is durable, authentic, traditional, natural. For example, the classical Japanese inrō (印籠) is a traditional design piece (carry-on multi compartment storage holder)  which is made out of bamboo, wood, ivory and other materials.

Apart from finding bamboo a better material choice, in (relatively) smaller production quantities it imho beats the costing aspects of producing / designing master molds for injection molding. 

Will make a nice render to show the design concept itself. 

![sketch-hw-wallet-proposal](https://user-images.githubusercontent.com/1434187/37706919-7ad63840-2d01-11e8-8520-05adc9ba14b4.jpg)

**Comment by ZeGermanSumo** [comment]
We have an awesome suggestion and nobody dares to make a new one because of it... Very good work! I'm excited to see this project succeed. I like the design, I like the suggestions you made.

**Comment by Matthewhnnh** [comment]
I agree with the German guy for once, good job.

**Comment by radbud** [comment]
Finally a proper thread on the hardware wallet and a drawing! Yay!

It sounds very functional and to the point. Personally i would not even bat an eye at the mention of using bamboo for such a device, but if i may argue for the case durability especially since it will potentially hold enormous amounts of value and for a long long time to come (fingers crossed), may i suggest Titanium.. It may sound as an overkill and make the device a bit more expensive, but it is virtually indestructible unless you are hell bent on trying to destroy it.  Bamboo even though i love the material and use it from my drinking cups to furniture and even my bicycle, has quite a few vulnerabilities, of note being Fire, Heavy enough loads and temperature/humidity changes making it flex enough to over time will develop warpage or crevices large enough for moisture to enter and affect not the bamboo itself, but the circuitry. While a titanium piece will probably outlast a few generations. Just thinking in terms of redundancy. I would like to minimize any inconsistency or uncertainty in a device which will hold a lot of value for me. I would sleep much better if the vault i hold my money was made of Titanium rather than Bamboo. Plus Titanium is as earthly, has weight and a rugged character that inspires trust. And i am not the paranoid types, but we have all kinds of people in the world.

Just my 2 cents.

Another thing, are you guys thinking of making it compatible with other cryptos, like Monero or Bitcoin?

Thank you for this!

**Comment by ZeGermanSumo** [comment]
This discussion came to a sad stop. What about it @gustavoz ? Shall me move on?
